version: '3.8'

services:

  back:
    image: shureck/panda_back:latest
    restart: always
    
    command: uvicorn main:app --reload --host 0.0.0.0

    # volumes:
    #     - ./zero_images/:/usr/src/zero_images/

    ports:
      - 8060:8000
  
  front:
    image: shureck/panda_front:latest
    volumes:
      - '/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true